"""more fields to calls

Revision ID: 056a32f1fa4a
Revises: ab1670855dfa
Create Date: 2025-12-06 16:18:45.653523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056a32f1fa4a'
down_revision: Union[str, Sequence[str], None] = 'ab1670855dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_1'), 'call_transcriptions', type_='foreignkey')
    op.create_foreign_key(None, 'call_transcriptions', 'calls', ['call_id'], ['id'], ondelete='CASCADE')
    op.add_column('calls', sa.Column('language', sa.String(length=255), nullable=False))
    op.add_column('calls', sa.Column('customer_name', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('fk_1'), 'tool_invocations', type_='foreignkey')
    op.create_foreign_key(None, 'tool_invocations', 'calls', ['call_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_3'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_1'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_2'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_4'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'tool_invocations', ['tool_invocation_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'bank_accounts', ['to_account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'bank_accounts', ['from_account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'calls', ['call_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_4'), 'transactions', 'tool_invocations', ['tool_invocation_id'], ['id'], referent_schema='test')
    op.create_foreign_key(op.f('fk_2'), 'transactions', 'bank_accounts', ['from_account_id'], ['id'], referent_schema='test')
    op.create_foreign_key(op.f('fk_1'), 'transactions', 'calls', ['call_id'], ['id'], referent_schema='test')
    op.create_foreign_key(op.f('fk_3'), 'transactions', 'bank_accounts', ['to_account_id'], ['id'], referent_schema='test')
    op.drop_constraint(None, 'tool_invocations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_1'), 'tool_invocations', 'calls', ['call_id'], ['id'], referent_schema='test', ondelete='CASCADE')
    op.drop_column('calls', 'customer_name')
    op.drop_column('calls', 'language')
    op.drop_constraint(None, 'call_transcriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_1'), 'call_transcriptions', 'calls', ['call_id'], ['id'], referent_schema='test', ondelete='CASCADE')
    # ### end Alembic commands ###
