"""delete tool call table

Revision ID: fd7c38fd3007
Revises: 784c26723c34
Create Date: 2025-12-06 20:58:07.915165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "fd7c38fd3007"
down_revision: Union[str, Sequence[str], None] = "784c26723c34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("fk_1"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_call_invoked"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_call_id"), table_name="tool_invocations")
    op.drop_table("tool_invocations")
    op.drop_index(op.f("ix_transactions_tool_invocation_id"), table_name="transactions")
    op.drop_column("transactions", "tool_invocation_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "tool_invocations",
        sa.Column(
            "id", mysql.BIGINT(display_width=20), autoincrement=True, nullable=False
        ),
        sa.Column(
            "call_id",
            mysql.BIGINT(display_width=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "tool_type",
            mysql.ENUM("TRANSFER_MONEY", "CHECK_BALANCE", "GET_HISTORY"),
            nullable=False,
        ),
        sa.Column("parameters", mysql.TEXT(), nullable=True),
        sa.Column("response", mysql.TEXT(), nullable=True),
        sa.Column(
            "success",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("error_message", mysql.TEXT(), nullable=True),
        sa.Column("invoked_at", mysql.DATETIME(), nullable=False),
        sa.Column("completed_at", mysql.DATETIME(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(), nullable=True),
        sa.Column("updated_at", mysql.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_id"], ["test.calls.id"], name=op.f("fk_2"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_bin",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_tool_invocations_call_id"),
        "tool_invocations",
        ["call_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tool_call_invoked"),
        "tool_invocations",
        ["call_id", "invoked_at"],
        unique=False,
    )
    op.create_index(op.f("fk_1"), "tool_invocations", ["call_id"], unique=False)

    op.add_column(
        "transactions",
        sa.Column(
            "tool_invocation_id",
            mysql.BIGINT(display_width=20),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_5"),
        "transactions",
        "tool_invocations",
        ["tool_invocation_id"],
        ["id"],
        referent_schema="test",
    )
    op.create_index(
        op.f("ix_transactions_tool_invocation_id"),
        "transactions",
        ["tool_invocation_id"],
        unique=False,
    )
    op.create_index(op.f("fk_4"), "transactions", ["tool_invocation_id"], unique=False)

    # ### end Alembic commands ###
