"""remove currency

Revision ID: 1752714d4b1d
Revises: c8c193e84df0
Create Date: 2025-12-06 17:55:43.348120

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1752714d4b1d"
down_revision: Union[str, Sequence[str], None] = "c8c193e84df0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bank_accounts", "currency")
    op.drop_column("transactions", "currency")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("currency", mysql.VARCHAR(length=3), nullable=False)
    )
    op.add_column(
        "bank_accounts", sa.Column("currency", mysql.VARCHAR(length=3), nullable=False)
    )
    # ### end Alembic commands ###
