"""add bill entity

Revision ID: 784c26723c34
Revises: 1752714d4b1d
Create Date: 2025-12-06 20:40:38.808459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "784c26723c34"
down_revision: Union[str, Sequence[str], None] = "1752714d4b1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bills",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "ELECTRICITY",
                "WATER",
                "GAS",
                "INTERNET",
                "TV",
                "PHONE",
                "PARKING",
                "OTHER",
                name="billtype",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", "OVERDUE", name="billstatus"),
            nullable=False,
        ),
        sa.Column("paid_from_account_id", sa.BigInteger(), nullable=True),
        sa.Column("transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["paid_from_account_id"],
            ["bank_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_bill_user_status", "bills", ["user_id", "status"], unique=False)
    op.create_index(
        op.f("ix_bills_paid_from_account_id"),
        "bills",
        ["paid_from_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bills_transaction_id"), "bills", ["transaction_id"], unique=False
    )
    op.create_index(op.f("ix_bills_user_id"), "bills", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bills_user_id"), table_name="bills")
    op.drop_index(op.f("ix_bills_transaction_id"), table_name="bills")
    op.drop_index(op.f("ix_bills_paid_from_account_id"), table_name="bills")
    op.drop_index("ix_bill_user_status", table_name="bills")
    op.drop_table("bills")
    # ### end Alembic commands ###
