"""add bank account title

Revision ID: c8c193e84df0
Revises: 056a32f1fa4a
Create Date: 2025-12-06 17:29:15.642742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8c193e84df0"
down_revision: Union[str, Sequence[str], None] = "056a32f1fa4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bank_accounts", sa.Column("title", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bank_accounts", "title")
    # ### end Alembic commands ###
