"""initial v2

Revision ID: 1f9f26c1d3ce
Revises: 
Create Date: 2026-01-06 12:57:49.778225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9f26c1d3ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CLOSED', name='accountstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_user_status', 'bank_accounts', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_bank_accounts_account_number'), 'bank_accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='callstatus'), nullable=False),
    sa.Column('call_sid', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_sid')
    )
    op.create_index('ix_call_user_scheduled', 'calls', ['user_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_calls_user_id'), 'calls', ['user_id'], unique=False)
    op.create_table('call_transcriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('call_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('offset_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_transcriptions_call_id'), 'call_transcriptions', ['call_id'], unique=False)
    op.create_index('ix_transcription_call_seq', 'call_transcriptions', ['call_id', 'sequence'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('from_account_id', sa.BigInteger(), nullable=True),
    sa.Column('to_account_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('type', sa.Enum('TRANSFER', 'DEPOSIT', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('call_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['from_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_from_created', 'transactions', ['from_account_id', 'created_at'], unique=False)
    op.create_index('ix_transaction_status', 'transactions', ['status'], unique=False)
    op.create_index('ix_transaction_to_created', 'transactions', ['to_account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_call_id'), 'transactions', ['call_id'], unique=False)
    op.create_index(op.f('ix_transactions_from_account_id'), 'transactions', ['from_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_transactions_to_account_id'), 'transactions', ['to_account_id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('ELECTRICITY', 'WATER', 'GAS', 'INTERNET', 'TV', 'PHONE', 'PARKING', 'OTHER', name='billtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', name='billstatus'), nullable=False),
    sa.Column('paid_from_account_id', sa.BigInteger(), nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paid_from_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bill_user_status', 'bills', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_bills_paid_from_account_id'), 'bills', ['paid_from_account_id'], unique=False)
    op.create_index(op.f('ix_bills_transaction_id'), 'bills', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_bills_user_id'), 'bills', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bills_user_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_transaction_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_paid_from_account_id'), table_name='bills')
    op.drop_index('ix_bill_user_status', table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_transactions_to_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_call_id'), table_name='transactions')
    op.drop_index('ix_transaction_to_created', table_name='transactions')
    op.drop_index('ix_transaction_status', table_name='transactions')
    op.drop_index('ix_transaction_from_created', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_transcription_call_seq', table_name='call_transcriptions')
    op.drop_index(op.f('ix_call_transcriptions_call_id'), table_name='call_transcriptions')
    op.drop_table('call_transcriptions')
    op.drop_index(op.f('ix_calls_user_id'), table_name='calls')
    op.drop_index('ix_call_user_scheduled', table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_account_number'), table_name='bank_accounts')
    op.drop_index('ix_account_user_status', table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
